name: cotept-local

services:
  oracle:
    image: gvenzl/oracle-xe:18-slim
    container_name: cotept-local-oracle
    env_file:
      - ./apps/api/.env
      - ./apps/api/.env.local
    environment:
      ORACLE_PASSWORD: ${DB_PASSWORD}
      APP_USER: ${DB_USER} # ADMIN 사용자 생성
      APP_USER_PASSWORD: ${DB_PASSWORD} # ADMIN 사용자의 비밀번호
      # 공통 환경변수 사용
      TZ: ${TZ}
    ports:
      - "${DB_PORT}:1521"
    volumes:
      - ./docker/oracle/local_data:/opt/oracle/oradata
      - ./docker/oracle/init.sql:/container-entrypoint-initdb.d/init.sql
    networks:
      - cotept-local
    healthcheck:
      test: ["CMD", "/opt/oracle/checkDBStatus.sh"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 240s
    restart: unless-stopped
    shm_size: 2g
    labels:
      - "com.cotept.description=Local Oracle 18c for CotePT API"
      - "com.cotept.version=${API_VERSION}"
  redis:
    image: redis:7-alpine
    container_name: cotept-local-redis
    command: redis-server /usr/local/etc/redis/redis.conf
    env_file:
      - ./apps/api/.env
      - ./apps/api/.env.local
    environment:
      # 공통 환경변수 사용
      TZ: ${TZ}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./docker/redis/local_data:/data
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - cotept-local
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    labels:
      - "com.cotept.description=Local Redis for CotePT API"
      - "com.cotept.version=${API_VERSION}"
  nosql:
    image: ghcr.io/oracle/nosql:latest-ce
    container_name: cotept-local-nosql
    hostname: nosql
    environment:
      TZ: ${TZ}
      KVHOST: nosql
      KV_PROXY_PORT: 8080
    ports:
      - "${NOSQL_PORT:-8080}:8080"
      - "${NOSQL_ADMIN_PORT:-5001}:5001" # 관리 포트 (선택사항)
    volumes:
      - ./docker/nosql/local_data:/kvroot
    networks:
      - cotept-local
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/V2/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    labels:
      - "com.cotept.description=Local Oracle NoSQL for CotePT API"
      - "com.cotept.version=${API_VERSION}"

networks:
  cotept-local:
    name: cotept-local
    driver: bridge
    labels:
      - "com.cotept.environment=local"
      - "com.cotept.version=${API_VERSION}"

volumes:
  oracle_local_data:
    name: cotept-local-oracle
  redis_local_data:
    name: cotept-local-redis
  nosql_local_data:
    name: cotept-local-nosql
