name: cotept-local

services:
  oracle:
    image: rollernaut/oracle19c:latest # ARM64 지원 비공식 이미지로 변경
    container_name: cotept-local-oracle
    env_file:
      - ./apps/api/.env
      - ./apps/api/.env.local
    environment:
      ORACLE_SID: ORCLCDB
      PATH: /opt/oracle/product/19c/dbhome_1/bin:$PATH
      ORACLE_PASSWORD: ${DB_PASSWORD}
      APP_USER: ${DB_USER}
      APP_USER_PASSWORD: ${DB_PASSWORD}
      TZ: ${TZ}
    ports:
      - "${DB_PORT}:1521"
    volumes:
      - ./docker/oracle/local_data:/opt/oracle/oradata
      - ./docker/oracle/init.sql:/container-entrypoint-initdb.d/init.sql
    networks:
      - cotept-local
    healthcheck:
      test: ["CMD", "ls", "/opt/oracle/oradata"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 240s
    restart: unless-stopped
    shm_size: 2g
    labels:
      - "com.cotept.description=Local Oracle 19c for CotePT API"
      - "com.cotept.version=${API_VERSION}"
