/* tslint:disable */
/* eslint-disable */
/**
 * CotePT API
 * 코딩 테스트 멘토링 플랫폼 API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Null } from './null';

/**
 * 
 * @export
 * @interface EmptyWrapper
 */
export interface EmptyWrapper {
    /**
     * 응답 메시지
     * @type {string}
     * @memberof EmptyWrapper
     */
    'message'?: string;
    /**
     * 응답 데이터 없음
     * @type {Null}
     * @memberof EmptyWrapper
     */
    'data'?: Null;
}

