openapi: 3.0.0
paths:
  /auth/login:
    post:
      operationId: AuthController_login
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginDto'
      responses:
        '200':
          description: 로그인 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponseDto'
        '401':
          description: 인증 실패 - 잘못된 이메일 또는 비밀번호
      tags: &ref_0
        - auth
  /auth/refresh:
    post:
      operationId: AuthController_refreshToken
      parameters: []
      responses:
        '200':
          description: 토큰 갱신 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponseDto'
        '401':
          description: 인증 실패 - 유효하지 않거나 만료된 토큰
      security:
        - access-token: []
      tags: *ref_0
info:
  title: CotePT API
  description: 코딩 테스트 멘토링 플랫폼 API
  version: '1.0'
  contact: {}
tags:
  - name: auth
    description: 인증 관련 API
  - name: mentee
    description: 멘티 관련 API
  - name: mentor
    description: 멘토 관련 API
  - name: mentoring
    description: 멘토링 관련 API
  - name: admin
    description: 관리자 관련 API
servers: []
components:
  securitySchemes:
    access-token:
      scheme: bearer
      bearerFormat: JWT
      type: http
      name: JWT
      description: JWT 토큰을 입력하세요
      in: header
  schemas:
    LoginDto:
      type: object
      properties:
        email:
          type: string
          description: 사용자 이메일
          example: user@example.com
        password:
          type: string
          description: 사용자 비밀번호
          example: password123
          minLength: 8
      required:
        - email
        - password
    LoginResponseDto:
      type: object
      properties:
        success:
          type: boolean
          description: 인증 성공 여부
          example: true
        accessToken:
          type: string
          description: 액세스 토큰
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        refreshToken:
          type: string
          description: 리프레시 토큰
          example: dsdsds...
        role:
          type: string
          description: 사용자 역할
          example: mentee
          enum:
            - mentee
            - mentor
            - admin
      required:
        - success
        - accessToken
        - refreshToken
        - role
