/* tslint:disable */
/* eslint-disable */
/**
 * CotePT API
 * 코딩 테스트 멘토링 플랫폼 API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ApiResponse
 */
export interface ApiResponse {
    /**
     * 응답 메시지
     * @type {string}
     * @memberof ApiResponse
     */
    'message'?: string;
    /**
     * 응답 데이터
     * @type {object}
     * @memberof ApiResponse
     */
    'data'?: object;
}

