/* tslint:disable */
/* eslint-disable */
/**
 * CotePT API
 * 코딩 테스트 멘토링 플랫폼 API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface LoginResponseDto
 */
export interface LoginResponseDto {
    /**
     * 인증 성공 여부
     * @type {boolean}
     * @memberof LoginResponseDto
     */
    'success': boolean;
    /**
     * 액세스 토큰
     * @type {string}
     * @memberof LoginResponseDto
     */
    'accessToken': string;
    /**
     * 리프레시 토큰
     * @type {string}
     * @memberof LoginResponseDto
     */
    'refreshToken': string;
    /**
     * 사용자 역할
     * @type {string}
     * @memberof LoginResponseDto
     */
    'role': LoginResponseDtoRoleEnum;
}

export const LoginResponseDtoRoleEnum = {
    Mentee: 'mentee',
    Mentor: 'mentor',
    Admin: 'admin'
} as const;

export type LoginResponseDtoRoleEnum = typeof LoginResponseDtoRoleEnum[keyof typeof LoginResponseDtoRoleEnum];


