/* tslint:disable */
/* eslint-disable */
/**
 * CotePT API
 * 코딩 테스트 멘토링 플랫폼 API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TokenResponseDto
 */
export interface TokenResponseDto {
    /**
     * 액세스 토큰
     * @type {string}
     * @memberof TokenResponseDto
     */
    'accessToken': string;
    /**
     * 리프레시 토큰
     * @type {string}
     * @memberof TokenResponseDto
     */
    'refreshToken': string;
    /**
     * 토큰 타입
     * @type {string}
     * @memberof TokenResponseDto
     */
    'tokenType': string;
    /**
     * 액세스 토큰 만료 시간(초)
     * @type {number}
     * @memberof TokenResponseDto
     */
    'expiresIn': number;
}

