/* tslint:disable */
/* eslint-disable */
/**
 * CotePT API
 * 코딩 테스트 멘토링 플랫폼 API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserResponseDto
 */
export interface UserResponseDto {
    /**
     * 사용자 고유 ID
     * @type {string}
     * @memberof UserResponseDto
     */
    'id': string;
    /**
     * 사용자 이메일
     * @type {string}
     * @memberof UserResponseDto
     */
    'email': string;
    /**
     * 사용자 이름
     * @type {string}
     * @memberof UserResponseDto
     */
    'name'?: string;
    /**
     * 사용자 역할
     * @type {string}
     * @memberof UserResponseDto
     */
    'role': UserResponseDtoRole;
    /**
     * 사용자 상태
     * @type {string}
     * @memberof UserResponseDto
     */
    'status': UserResponseDtoStatus;
    /**
     * 전화번호
     * @type {string}
     * @memberof UserResponseDto
     */
    'phoneNumber'?: string;
    /**
     * 전화번호 인증 여부
     * @type {boolean}
     * @memberof UserResponseDto
     */
    'phoneVerified'?: boolean;
    /**
     * 사용자 생성일
     * @type {string}
     * @memberof UserResponseDto
     */
    'createdAt': string;
    /**
     * 사용자 정보 수정일
     * @type {string}
     * @memberof UserResponseDto
     */
    'updatedAt': string;
    /**
     * 마지막 로그인 일시
     * @type {string}
     * @memberof UserResponseDto
     */
    'lastLoginAt'?: string;
}

export const UserResponseDtoRole = {
    Mentee: 'MENTEE',
    Mentor: 'MENTOR',
    Admin: 'ADMIN'
} as const;

export type UserResponseDtoRole = typeof UserResponseDtoRole[keyof typeof UserResponseDtoRole];
export const UserResponseDtoStatus = {
    Active: 'ACTIVE',
    Inactive: 'INACTIVE',
    Suspended: 'SUSPENDED'
} as const;

export type UserResponseDtoStatus = typeof UserResponseDtoStatus[keyof typeof UserResponseDtoStatus];


