/* tslint:disable */
/* eslint-disable */
/**
 * CotePT API
 * 코딩 테스트 멘토링 플랫폼 API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ApiResponse } from './api-response';
// May contain unused imports in some cases
// @ts-ignore
import type { UserResponseDto } from './user-response-dto';

/**
 * @type UserControllerGetUserById200Response
 * @export
 */
export type UserControllerGetUserById200Response = ApiResponse;


