/* tslint:disable */
/* eslint-disable */
/**
 * CotePT API
 * 코딩 테스트 멘토링 플랫폼 API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ValidateTokenRequestDto
 */
export interface ValidateTokenRequestDto {
    /**
     * 검증할 액세스 토큰
     * @type {string}
     * @memberof ValidateTokenRequestDto
     */
    'token': string;
}

