/* tslint:disable */
/* eslint-disable */
/**
 * CotePT API
 * 코딩 테스트 멘토링 플랫폼 API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MailRequestDtoAttachmentsInner } from './mail-request-dto-attachments-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { MailRequestDtoTo } from './mail-request-dto-to';

/**
 * 
 * @export
 * @interface MailRequestDto
 */
export interface MailRequestDto {
    /**
     * 
     * @type {MailRequestDtoTo}
     * @memberof MailRequestDto
     */
    'to': MailRequestDtoTo;
    /**
     * 템플릿 유형
     * @type {string}
     * @memberof MailRequestDto
     */
    'template': Template;
    /**
     * 템플릿 컨텍스트 (변수)
     * @type {object}
     * @memberof MailRequestDto
     */
    'data': object;
    /**
     * 언어 설정
     * @type {string}
     * @memberof MailRequestDto
     */
    'locale'?: Locale;
    /**
     * 첨부 파일
     * @type {Array<MailRequestDtoAttachmentsInner>}
     * @memberof MailRequestDto
     */
    'attachments'?: Array<MailRequestDtoAttachmentsInner>;
}

/**
    * @export
    * @enum {string}
    */
export enum Template {
    emailVerification = 'email_verification',
    passwordRecovery = 'password_recovery',
    reservationCreate = 'reservation_create',
    reservationFix = 'reservation_fix',
    reservationCancel = 'reservation_cancel',
    reservationChange = 'reservation_change',
    reservationPrenotice = 'reservation_prenotice',
    verificationCode = 'verification_code'
}
/**
    * @export
    * @enum {string}
    */
export enum Locale {
    ko = 'ko',
    en = 'en'
}


