/* tslint:disable */
/* eslint-disable */
/**
 * CotePT API
 * 코딩 테스트 멘토링 플랫폼 API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MailAuditResponseDto
 */
export interface MailAuditResponseDto {
    /**
     * 메일 감사 ID
     * @type {string}
     * @memberof MailAuditResponseDto
     */
    'id': string;
    /**
     * 메일 ID
     * @type {string}
     * @memberof MailAuditResponseDto
     */
    'mailId': string;
    /**
     * 메일 템플릿
     * @type {string}
     * @memberof MailAuditResponseDto
     */
    'template': string;
    /**
     * 수신자 목록
     * @type {Array<string>}
     * @memberof MailAuditResponseDto
     */
    'recipients': Array<string>;
    /**
     * 메일 상태
     * @type {string}
     * @memberof MailAuditResponseDto
     */
    'status': Status;
    /**
     * 생성 시간
     * @type {string}
     * @memberof MailAuditResponseDto
     */
    'createdAt': string;
    /**
     * 메일 컨텍스트 데이터
     * @type {object}
     * @memberof MailAuditResponseDto
     */
    'context': object;
    /**
     * 언어 설정
     * @type {string}
     * @memberof MailAuditResponseDto
     */
    'locale': string;
    /**
     * 발송 시간
     * @type {string}
     * @memberof MailAuditResponseDto
     */
    'sentAt'?: string | null;
    /**
     * 오류 메시지
     * @type {string}
     * @memberof MailAuditResponseDto
     */
    'error'?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum Status {
    pending = 'PENDING',
    sent = 'SENT',
    failed = 'FAILED'
}


