import { MigrationInterface, QueryRunner } from "typeorm";

export class Migration20250926004822 implements MigrationInterface {
    name = 'Migration20250926004822'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
            CREATE TABLE "MENTOR_TAGS" (
                "idx" number GENERATED BY DEFAULT AS IDENTITY,
                "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
                "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
                "name" varchar2(50) NOT NULL,
                "category" varchar2(20) NOT NULL,
                "display_order" number DEFAULT 0 NOT NULL,
                "is_active" number DEFAULT 1 NOT NULL,
                CONSTRAINT "PK_31de952ad11d938be37c7cc68d8" PRIMARY KEY ("idx")
            )
        `);
        await queryRunner.query(`
            CREATE TABLE "MENTOR_PROFILE_TAGS" (
                "idx" number GENERATED BY DEFAULT AS IDENTITY,
                "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
                "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
                "mentor_profile_id" number,
                "mentor_tag_id" number,
                CONSTRAINT "PK_15aa9cec6667c7d2b6989a110d1" PRIMARY KEY ("idx")
            )
        `);
        await queryRunner.query(`
            CREATE TABLE "MENTOR_PROFILES" (
                "idx" number GENERATED BY DEFAULT AS IDENTITY,
                "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
                "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
                "cotept_user_id" varchar2(36) NOT NULL,
                "introduction_title" varchar2(100),
                "introduction_content" clob,
                "baekjoon_tier_display" number DEFAULT 1 NOT NULL,
                "mentoring_count" number DEFAULT 0 NOT NULL,
                "total_review_count" number DEFAULT 0 NOT NULL,
                "average_rating" number(3, 2) DEFAULT 0 NOT NULL,
                "is_verified" number DEFAULT 0 NOT NULL,
                "is_active" number DEFAULT 1 NOT NULL,
                "profile_completion" number DEFAULT 0 NOT NULL,
                "user_id" number,
                CONSTRAINT "REL_033ba3a134a8e333a20ade62cd" UNIQUE ("user_id"),
                CONSTRAINT "PK_08b267eaade1dcc17541c85b84c" PRIMARY KEY ("idx")
            )
        `);
        await queryRunner.query(`
            CREATE TABLE "ONBOARDING_STATES" (
                "idx" number GENERATED BY DEFAULT AS IDENTITY,
                "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
                "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
                "userId" varchar2(36) NOT NULL,
                "currentStep" number DEFAULT 1 NOT NULL,
                "profileCreated" number DEFAULT 0 NOT NULL,
                "baekjoonVerified" number DEFAULT 0 NOT NULL,
                "skillAnalysisCompleted" number DEFAULT 0 NOT NULL,
                "mentorProfileCreated" number DEFAULT 0 NOT NULL,
                "completedAt" timestamp,
                CONSTRAINT "PK_355778a880c8e13b3f2ceca7c0f" PRIMARY KEY ("idx", "userId")
            )
        `);
        await queryRunner.query(`
            ALTER TABLE "BAEKJOON_PROFILE"
            MODIFY "is_mentor_eligible" number(1) DEFAULT 0
        `);
        await queryRunner.query(`
            ALTER TABLE "MENTOR_PROFILE_TAGS"
            ADD CONSTRAINT "FK_e1bd78b07af3d6ba568d8a0a8a8" FOREIGN KEY ("mentor_profile_id") REFERENCES "MENTOR_PROFILES" ("idx") ON DELETE CASCADE
        `);
        await queryRunner.query(`
            ALTER TABLE "MENTOR_PROFILE_TAGS"
            ADD CONSTRAINT "FK_d1e845cca2a154d35d7ea0268dd" FOREIGN KEY ("mentor_tag_id") REFERENCES "MENTOR_TAGS" ("idx") ON DELETE CASCADE
        `);
        await queryRunner.query(`
            ALTER TABLE "MENTOR_PROFILES"
            ADD CONSTRAINT "FK_033ba3a134a8e333a20ade62cde" FOREIGN KEY ("user_id") REFERENCES "USERS" ("idx") ON DELETE CASCADE
        `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
            ALTER TABLE "MENTOR_PROFILES" DROP CONSTRAINT "FK_033ba3a134a8e333a20ade62cde"
        `);
        await queryRunner.query(`
            ALTER TABLE "MENTOR_PROFILE_TAGS" DROP CONSTRAINT "FK_d1e845cca2a154d35d7ea0268dd"
        `);
        await queryRunner.query(`
            ALTER TABLE "MENTOR_PROFILE_TAGS" DROP CONSTRAINT "FK_e1bd78b07af3d6ba568d8a0a8a8"
        `);
        await queryRunner.query(`
            ALTER TABLE "BAEKJOON_PROFILE"
            MODIFY "is_mentor_eligible" number(1, 0) DEFAULT 0
        `);
        await queryRunner.query(`
            DROP TABLE "ONBOARDING_STATES"
        `);
        await queryRunner.query(`
            DROP TABLE "MENTOR_PROFILES"
        `);
        await queryRunner.query(`
            DROP TABLE "MENTOR_PROFILE_TAGS"
        `);
        await queryRunner.query(`
            DROP TABLE "MENTOR_TAGS"
        `);
    }

}
