import { MigrationInterface, QueryRunner } from "typeorm";

export class Migration20250909231236 implements MigrationInterface {
    name = 'Migration20250909231236'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
            CREATE TABLE "USER_PROFILES" (
                "idx" number GENERATED BY DEFAULT AS IDENTITY,
                "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
                "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
                "cotept_user_id" varchar2(36) NOT NULL,
                "nickname" varchar2(50) NOT NULL,
                "full_name" varchar2(100),
                "introduce" varchar2(280),
                "profile_image_url" varchar2(1000),
                "user_id" number,
                CONSTRAINT "REL_48ee21ddee7e59b310669f6b71" UNIQUE ("user_id"),
                CONSTRAINT "PK_964b0edfc4119358847a2cda707" PRIMARY KEY ("idx")
            )
        `);
        await queryRunner.query(`
            ALTER TABLE "BAEKJOON_PROFILE"
            MODIFY "is_mentor_eligible" number(1) DEFAULT 0
        `);
        await queryRunner.query(`
            ALTER TABLE "USER_PROFILES"
            ADD CONSTRAINT "FK_48ee21ddee7e59b310669f6b710" FOREIGN KEY ("user_id") REFERENCES "USERS" ("idx") ON DELETE CASCADE
        `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
            ALTER TABLE "USER_PROFILES" DROP CONSTRAINT "FK_48ee21ddee7e59b310669f6b710"
        `);
        await queryRunner.query(`
            ALTER TABLE "BAEKJOON_PROFILE"
            MODIFY "is_mentor_eligible" number(1, 0) DEFAULT 0
        `);
        await queryRunner.query(`
            DROP TABLE "USER_PROFILES"
        `);
    }

}
