/* tslint:disable */
/* eslint-disable */
/**
 * CotePT API
 * 코딩 테스트 멘토링 플랫폼 API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ChangePasswordRequestDto
 */
export interface ChangePasswordRequestDto {
    /**
     * 현재 비밀번호
     * @type {string}
     * @memberof ChangePasswordRequestDto
     */
    'currentPassword': string;
    /**
     * 새 비밀번호 (8~32자, 대소문자, 숫자, 특수문자 포함)
     * @type {string}
     * @memberof ChangePasswordRequestDto
     */
    'newPassword': string;
    /**
     * 새 비밀번호 확인
     * @type {string}
     * @memberof ChangePasswordRequestDto
     */
    'confirmPassword': string;
}

