/* tslint:disable */
/* eslint-disable */
/**
 * CotePT API
 * 코딩 테스트 멘토링 플랫폼 API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateUserRequestDto
 */
export interface CreateUserRequestDto {
    /**
     * 사용자 이메일
     * @type {string}
     * @memberof CreateUserRequestDto
     */
    'email': string;
    /**
     * 비밀번호 (8~32자, 대소문자, 숫자, 특수문자 포함)
     * @type {string}
     * @memberof CreateUserRequestDto
     */
    'password': string;
    /**
     * 사용자 이름 (2~50자, 한글/영문만 허용)
     * @type {string}
     * @memberof CreateUserRequestDto
     */
    'name'?: string;
    /**
     * 전화번호 (- 없이 숫자만)
     * @type {string}
     * @memberof CreateUserRequestDto
     */
    'phoneNumber'?: string;
    /**
     * 사용자 역할 (기본값: MENTEE)
     * @type {string}
     * @memberof CreateUserRequestDto
     */
    'role'?: Role;
}

/**
    * @export
    * @enum {string}
    */
export enum Role {
    mentee = 'MENTEE',
    mentor = 'MENTOR'
}


