/* tslint:disable */
/* eslint-disable */
/**
 * CotePT API
 * 코딩 테스트 멘토링 플랫폼 API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetAllUsers403Response
 */
export interface GetAllUsers403Response {
    /**
     * 
     * @type {number}
     * @memberof GetAllUsers403Response
     */
    'statusCode'?: number;
    /**
     * 
     * @type {string}
     * @memberof GetAllUsers403Response
     */
    'message'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAllUsers403Response
     */
    'timestamp'?: string;
}

