/* tslint:disable */
/* eslint-disable */
/**
 * CotePT API
 * 코딩 테스트 멘토링 플랫폼 API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ConfirmSocialLinkRequestDto
 */
export interface ConfirmSocialLinkRequestDto {
    /**
     * 임시 연결 토큰
     * @type {string}
     * @memberof ConfirmSocialLinkRequestDto
     */
    'token': string;
    /**
     * 계정 연결 승인 여부
     * @type {boolean}
     * @memberof ConfirmSocialLinkRequestDto
     */
    'approved': boolean;
}

