/* tslint:disable */
/* eslint-disable */
/**
 * CotePT API
 * 코딩 테스트 멘토링 플랫폼 API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FindIdRequestDto
 */
export interface FindIdRequestDto {
    /**
     * 인증 방식 (\'EMAIL\' 또는 \'PHONE\')
     * @type {string}
     * @memberof FindIdRequestDto
     */
    'authType': AuthType;
    /**
     * 인증 대상 (이메일 주소 또는 전화번호)
     * @type {string}
     * @memberof FindIdRequestDto
     */
    'target': string;
    /**
     * 인증 ID (인증 코드 발송 후 받은 ID)
     * @type {string}
     * @memberof FindIdRequestDto
     */
    'verificationId': string;
    /**
     * 인증 코드
     * @type {string}
     * @memberof FindIdRequestDto
     */
    'verificationCode': string;
}

/**
    * @export
    * @enum {string}
    */
export enum AuthType {
    email = 'EMAIL',
    phone = 'PHONE'
}


