/* tslint:disable */
/* eslint-disable */
/**
 * CotePT API
 * 코딩 테스트 멘토링 플랫폼 API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface LoginRequestDto
 */
export interface LoginRequestDto {
    /**
     * 사용자 아이디
     * @type {string}
     * @memberof LoginRequestDto
     */
    'id': string;
    /**
     * 사용자 비밀번호
     * @type {string}
     * @memberof LoginRequestDto
     */
    'password': string;
}

