/* tslint:disable */
/* eslint-disable */
/**
 * CotePT API
 * 코딩 테스트 멘토링 플랫폼 API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface VerifyCodeRequestDto
 */
export interface VerifyCodeRequestDto {
    /**
     * 검증 ID
     * @type {string}
     * @memberof VerifyCodeRequestDto
     */
    'verificationId': string;
    /**
     * 인증 코드 (6자리)
     * @type {string}
     * @memberof VerifyCodeRequestDto
     */
    'code': string;
}

