/* tslint:disable */
/* eslint-disable */
/**
 * CotePT API
 * 코딩 테스트 멘토링 플랫폼 API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AvailabilityResponseDto
 */
export interface AvailabilityResponseDto {
    /**
     * 사용 가능 여부
     * @type {boolean}
     * @memberof AvailabilityResponseDto
     */
    'available': boolean;
    /**
     * 메시지 (중복 시에만 표시)
     * @type {string}
     * @memberof AvailabilityResponseDto
     */
    'message'?: string;
}

