/* tslint:disable */
/* eslint-disable */
/**
 * CotePT API
 * 코딩 테스트 멘토링 플랫폼 API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BaekjoonProfileResponseDto
 */
export interface BaekjoonProfileResponseDto {
    /**
     * 사용자 ID
     * @type {string}
     * @memberof BaekjoonProfileResponseDto
     */
    'userId': string;
    /**
     * 백준 ID
     * @type {string}
     * @memberof BaekjoonProfileResponseDto
     */
    'handle': string;
    /**
     * 현재 티어
     * @type {string}
     * @memberof BaekjoonProfileResponseDto
     */
    'tier': string;
    /**
     * 레이팅
     * @type {number}
     * @memberof BaekjoonProfileResponseDto
     */
    'rating': number;
    /**
     * 전체 순위
     * @type {number}
     * @memberof BaekjoonProfileResponseDto
     */
    'rank': number;
    /**
     * 해결한 문제 수
     * @type {number}
     * @memberof BaekjoonProfileResponseDto
     */
    'solvedCount': number;
    /**
     * 마지막 업데이트 시간
     * @type {string}
     * @memberof BaekjoonProfileResponseDto
     */
    'lastUpdated': string;
    /**
     * 멘토 자격 여부 (Platinum 3 이상)
     * @type {boolean}
     * @memberof BaekjoonProfileResponseDto
     */
    'isMentorEligible': boolean;
    /**
     * 프로필 이미지 URL
     * @type {string}
     * @memberof BaekjoonProfileResponseDto
     */
    'profileImageUrl'?: string;
    /**
     * 사용자 bio
     * @type {string}
     * @memberof BaekjoonProfileResponseDto
     */
    'bio'?: string;
}

