/* tslint:disable */
/* eslint-disable */
/**
 * CotePT API
 * 코딩 테스트 멘토링 플랫폼 API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BasicProfileCreationResponseDtoCompleteness } from './basic-profile-creation-response-dto-completeness';
// May contain unused imports in some cases
// @ts-ignore
import type { UserProfileDto } from './user-profile-dto';

/**
 * 
 * @export
 * @interface BasicProfileCreationResponseDto
 */
export interface BasicProfileCreationResponseDto {
    /**
     * 생성된 기본 프로필 정보
     * @type {UserProfileDto}
     * @memberof BasicProfileCreationResponseDto
     */
    'profile': UserProfileDto;
    /**
     * 
     * @type {BasicProfileCreationResponseDtoCompleteness}
     * @memberof BasicProfileCreationResponseDto
     */
    'completeness': BasicProfileCreationResponseDtoCompleteness;
    /**
     * 다음 단계 가이드 메시지
     * @type {Array<string>}
     * @memberof BasicProfileCreationResponseDto
     */
    'nextSteps': Array<string>;
    /**
     * 응답 메시지
     * @type {string}
     * @memberof BasicProfileCreationResponseDto
     */
    'message': string;
    /**
     * 완성도 점수 (0-100)
     * @type {number}
     * @memberof BasicProfileCreationResponseDto
     */
    'completenessScore': number;
}

