/* tslint:disable */
/* eslint-disable */
/**
 * CotePT API
 * 코딩 테스트 멘토링 플랫폼 API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 프로필 완성도 정보
 * @export
 * @interface BasicProfileCreationResponseDtoCompleteness
 */
export interface BasicProfileCreationResponseDtoCompleteness {
    /**
     * 기본 정보 완성 여부
     * @type {boolean}
     * @memberof BasicProfileCreationResponseDtoCompleteness
     */
    'hasBasicInfo'?: boolean;
    /**
     * 프로필 완성 여부
     * @type {boolean}
     * @memberof BasicProfileCreationResponseDtoCompleteness
     */
    'isComplete'?: boolean;
    /**
     * 누락된 필드들
     * @type {Array<string>}
     * @memberof BasicProfileCreationResponseDtoCompleteness
     */
    'missingFields'?: Array<string>;
}

