/* tslint:disable */
/* eslint-disable */
/**
 * CotePT API
 * 코딩 테스트 멘토링 플랫폼 API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CheckEmailAvailabilityRequestDto
 */
export interface CheckEmailAvailabilityRequestDto {
    /**
     * 확인할 이메일 주소
     * @type {string}
     * @memberof CheckEmailAvailabilityRequestDto
     */
    'email': string;
}

