/* tslint:disable */
/* eslint-disable */
/**
 * CotePT API
 * 코딩 테스트 멘토링 플랫폼 API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CompleteBaekjoonVerificationDto
 */
export interface CompleteBaekjoonVerificationDto {
    /**
     * 사용자 ID
     * @type {string}
     * @memberof CompleteBaekjoonVerificationDto
     */
    'userId': string;
    /**
     * 백준 핸들
     * @type {string}
     * @memberof CompleteBaekjoonVerificationDto
     */
    'baekjoonHandle': string;
    /**
     * 인증 세션 ID
     * @type {string}
     * @memberof CompleteBaekjoonVerificationDto
     */
    'verificationSessionId': string;
}

