/* tslint:disable */
/* eslint-disable */
/**
 * CotePT API
 * 코딩 테스트 멘토링 플랫폼 API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CompleteVerificationRequestDto
 */
export interface CompleteVerificationRequestDto {
    /**
     * 인증 세션 ID
     * @type {string}
     * @memberof CompleteVerificationRequestDto
     */
    'sessionId': string;
    /**
     * 사용자 이메일
     * @type {string}
     * @memberof CompleteVerificationRequestDto
     */
    'email': string;
    /**
     * 백준 ID (사용자명)
     * @type {string}
     * @memberof CompleteVerificationRequestDto
     */
    'handle': string;
}

