/* tslint:disable */
/* eslint-disable */
/**
 * CotePT API
 * 코딩 테스트 멘토링 플랫폼 API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateUserProfileRequestDto
 */
export interface CreateUserProfileRequestDto {
    /**
     * 사용자 로그인 아이디 (User 모듈에서 기존 검증된 사용자)
     * @type {string}
     * @memberof CreateUserProfileRequestDto
     */
    'userId': string;
    /**
     * 닉네임 (2~50자, 한글/영문/숫자만 허용) - 필수
     * @type {string}
     * @memberof CreateUserProfileRequestDto
     */
    'nickname': string;
    /**
     * 자기소개 (280자 이하, 트위터 스타일)
     * @type {string}
     * @memberof CreateUserProfileRequestDto
     */
    'introduce'?: string;
    /**
     * 프로필 이미지 URL
     * @type {string}
     * @memberof CreateUserProfileRequestDto
     */
    'profileImageUrl'?: string;
}

