/* tslint:disable */
/* eslint-disable */
/**
 * CotePT API
 * 코딩 테스트 멘토링 플랫폼 API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateBasicProfileDto
 */
export interface CreateBasicProfileDto {
    /**
     * 사용자 로그인 아이디 (6~20자, 영문/숫자/특수문자)
     * @type {string}
     * @memberof CreateBasicProfileDto
     */
    'userId': string;
    /**
     * 닉네임 (2~50자, 한글/영문만 허용)
     * @type {string}
     * @memberof CreateBasicProfileDto
     */
    'nickname': string;
    /**
     * 프로필 이미지 URL
     * @type {string}
     * @memberof CreateBasicProfileDto
     */
    'profileImageUrl'?: string;
}

