/* tslint:disable */
/* eslint-disable */
/**
 * CotePT API
 * 코딩 테스트 멘토링 플랫폼 API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateMentorProfileDto
 */
export interface CreateMentorProfileDto {
    /**
     * 사용자 ID
     * @type {string}
     * @memberof CreateMentorProfileDto
     */
    'userId': string;
    /**
     * 멘토 태그 ID 목록
     * @type {Array<number>}
     * @memberof CreateMentorProfileDto
     */
    'tagIds': Array<number>;
    /**
     * 멘토 소개 제목
     * @type {string}
     * @memberof CreateMentorProfileDto
     */
    'introductionTitle'?: string;
    /**
     * 멘토 소개 내용
     * @type {string}
     * @memberof CreateMentorProfileDto
     */
    'introductionContent'?: string;
}

