/* tslint:disable */
/* eslint-disable */
/**
 * CotePT API
 * 코딩 테스트 멘토링 플랫폼 API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DeleteUserRequestDto
 */
export interface DeleteUserRequestDto {
    /**
     * 삭제 사유
     * @type {string}
     * @memberof DeleteUserRequestDto
     */
    'reason'?: string;
    /**
     * 삭제 확인을 위한 비밀번호
     * @type {string}
     * @memberof DeleteUserRequestDto
     */
    'password'?: string;
}

