export namespace extraEnums {
    
  export const TierColor = {
    Unrated: "#2D2D2D",
BronzeV: "#AD5600",
BronzeIV: "#AD5600",
BronzeIII: "#AD5600",
BronzeII: "#AD5600",
BronzeI: "#AD5600",
SilverV: "#435F7A",
SilverIV: "#435F7A",
SilverIII: "#435F7A",
SilverII: "#435F7A",
SilverI: "#435F7A",
GoldV: "#EC9A00",
GoldIV: "#EC9A00",
GoldIII: "#EC9A00",
GoldII: "#EC9A00",
GoldI: "#EC9A00",
PlatinumV: "#27E2A4",
PlatinumIV: "#27E2A4",
PlatinumIII: "#27E2A4",
PlatinumII: "#27E2A4",
PlatinumI: "#27E2A4",
DiamondV: "#00D2F0",
DiamondIV: "#00D2F0",
DiamondIII: "#00D2F0",
DiamondII: "#00D2F0",
DiamondI: "#00D2F0",
RubyV: "#FF0062",
RubyIV: "#FF0062",
RubyIII: "#FF0062",
RubyII: "#FF0062",
RubyI: "#FF0062",
Master: "#B491FF"
  } as const;
      

  export const TierName = {
    Unrated: "Unrated",
BronzeV: "BronzeV",
BronzeIV: "BronzeIV",
BronzeIII: "BronzeIII",
BronzeII: "BronzeII",
BronzeI: "BronzeI",
SilverV: "SilverV",
SilverIV: "SilverIV",
SilverIII: "SilverIII",
SilverII: "SilverII",
SilverI: "SilverI",
GoldV: "GoldV",
GoldIV: "GoldIV",
GoldIII: "GoldIII",
GoldII: "GoldII",
GoldI: "GoldI",
PlatinumV: "PlatinumV",
PlatinumIV: "PlatinumIV",
PlatinumIII: "PlatinumIII",
PlatinumII: "PlatinumII",
PlatinumI: "PlatinumI",
DiamondV: "DiamondV",
DiamondIV: "DiamondIV",
DiamondIII: "DiamondIII",
DiamondII: "DiamondII",
DiamondI: "DiamondI",
RubyV: "RubyV",
RubyIV: "RubyIV",
RubyIII: "RubyIII",
RubyII: "RubyII",
RubyI: "RubyI",
Master: "Master"
  } as const;
      
}