/* tslint:disable */
/* eslint-disable */
/**
 * CotePT API
 * 코딩 테스트 멘토링 플랫폼 API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GenerateUploadUrlResponseDto
 */
export interface GenerateUploadUrlResponseDto {
    /**
     * 파일을 업로드할 수 있는 Pre-signed URL
     * @type {string}
     * @memberof GenerateUploadUrlResponseDto
     */
    'uploadUrl': string;
    /**
     * 업로드 성공 후 파일에 접근할 수 있는 최종 URL
     * @type {string}
     * @memberof GenerateUploadUrlResponseDto
     */
    'fileUrl': string;
}

