/* tslint:disable */
/* eslint-disable */
/**
 * CotePT API
 * 코딩 테스트 멘토링 플랫폼 API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GenerateUploadUrlRequestDto
 */
export interface GenerateUploadUrlRequestDto {
    /**
     * 업로드할 파일의 이름 (확장자 포함)
     * @type {string}
     * @memberof GenerateUploadUrlRequestDto
     */
    'fileName': string;
    /**
     * 파일의 Content-Type (MIME 타입)
     * @type {string}
     * @memberof GenerateUploadUrlRequestDto
     */
    'contentType': string;
}

