/* tslint:disable */
/* eslint-disable */
/**
 * CotePT API
 * 코딩 테스트 멘토링 플랫폼 API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MailAuditResponseDto } from './mail-audit-response-dto';

/**
 * 
 * @export
 * @interface MailAuditResponseWrapper
 */
export interface MailAuditResponseWrapper {
    /**
     * 응답 메시지
     * @type {string}
     * @memberof MailAuditResponseWrapper
     */
    'message'?: string;
    /**
     * 
     * @type {MailAuditResponseDto}
     * @memberof MailAuditResponseWrapper
     */
    'data'?: MailAuditResponseDto;
}

