/* tslint:disable */
/* eslint-disable */
/**
 * CotePT API
 * 코딩 테스트 멘토링 플랫폼 API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MentorEligibilityDto
 */
export interface MentorEligibilityDto {
    /**
     * 멘토 자격 충족 여부
     * @type {boolean}
     * @memberof MentorEligibilityDto
     */
    'isEligible': boolean;
    /**
     * 현재 백준 티어
     * @type {string}
     * @memberof MentorEligibilityDto
     */
    'currentTier': string;
    /**
     * 멘토 자격 요건
     * @type {string}
     * @memberof MentorEligibilityDto
     */
    'requirement': string;
}

