/* tslint:disable */
/* eslint-disable */
/**
 * CotePT API
 * 코딩 테스트 멘토링 플랫폼 API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MentorTagDto } from './mentor-tag-dto';

/**
 * 
 * @export
 * @interface MentorProfileDto
 */
export interface MentorProfileDto {
    /**
     * 멘토 프로필 IDX
     * @type {number}
     * @memberof MentorProfileDto
     */
    'idx': number;
    /**
     * 연결된 유저의 고유 ID
     * @type {string}
     * @memberof MentorProfileDto
     */
    'userId': string;
    /**
     * 백준 티어 표시 여부
     * @type {boolean}
     * @memberof MentorProfileDto
     */
    'baekjoonTierDisplay': boolean;
    /**
     * 총 멘토링 횟수
     * @type {number}
     * @memberof MentorProfileDto
     */
    'mentoringCount': number;
    /**
     * 총 리뷰 개수
     * @type {number}
     * @memberof MentorProfileDto
     */
    'totalReviewCount': number;
    /**
     * 평균 평점 (0.0 ~ 5.0)
     * @type {number}
     * @memberof MentorProfileDto
     */
    'averageRating': number;
    /**
     * 멘토 인증 여부
     * @type {boolean}
     * @memberof MentorProfileDto
     */
    'isVerified': boolean;
    /**
     * 멘토 활동 여부
     * @type {boolean}
     * @memberof MentorProfileDto
     */
    'isActive': boolean;
    /**
     * 프로필 완성도 (0 ~ 100)
     * @type {number}
     * @memberof MentorProfileDto
     */
    'profileCompletion': number;
    /**
     * 멘토 태그 목록
     * @type {Array<MentorTagDto>}
     * @memberof MentorProfileDto
     */
    'tags': Array<MentorTagDto>;
    /**
     * 생성일
     * @type {string}
     * @memberof MentorProfileDto
     */
    'createdAt': string;
    /**
     * 수정일
     * @type {string}
     * @memberof MentorProfileDto
     */
    'updatedAt': string;
    /**
     * 멘토링 소개 제목
     * @type {string}
     * @memberof MentorProfileDto
     */
    'introductionTitle'?: string;
    /**
     * 멘토링 소개 내용 (마크다운)
     * @type {string}
     * @memberof MentorProfileDto
     */
    'introductionContent'?: string;
}

