/* tslint:disable */
/* eslint-disable */
/**
 * CotePT API
 * 코딩 테스트 멘토링 플랫폼 API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MentorTagDto } from './mentor-tag-dto';

/**
 * 
 * @export
 * @interface MentorTagsResponseDto
 */
export interface MentorTagsResponseDto {
    /**
     * 직무 태그 목록
     * @type {Array<MentorTagDto>}
     * @memberof MentorTagsResponseDto
     */
    'jobTags': Array<MentorTagDto>;
    /**
     * 연차 태그 목록
     * @type {Array<MentorTagDto>}
     * @memberof MentorTagsResponseDto
     */
    'experienceTags': Array<MentorTagDto>;
    /**
     * 회사 태그 목록
     * @type {Array<MentorTagDto>}
     * @memberof MentorTagsResponseDto
     */
    'companyTags': Array<MentorTagDto>;
}

