/* tslint:disable */
/* eslint-disable */
/**
 * CotePT API
 * 코딩 테스트 멘토링 플랫폼 API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { UserProfileDto } from './user-profile-dto';

/**
 * 
 * @export
 * @interface MyProfileResponseDto
 */
export interface MyProfileResponseDto {
    /**
     * 멘티 프로필 정보
     * @type {UserProfileDto}
     * @memberof MyProfileResponseDto
     */
    'menteeProfile': UserProfileDto;
    /**
     * 멘토 프로필 보유 여부
     * @type {boolean}
     * @memberof MyProfileResponseDto
     */
    'hasMentorProfile': boolean;
    /**
     * 멘토 프로필 ID (멘토인 경우)
     * @type {number}
     * @memberof MyProfileResponseDto
     */
    'mentorProfileId'?: number;
}

