/* tslint:disable */
/* eslint-disable */
/**
 * CotePT API
 * 코딩 테스트 멘토링 플랫폼 API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OnboardingStateResponseDto
 */
export interface OnboardingStateResponseDto {
    /**
     * 사용자 ID
     * @type {string}
     * @memberof OnboardingStateResponseDto
     */
    'userId': string;
    /**
     * 현재 온보딩 단계
     * @type {number}
     * @memberof OnboardingStateResponseDto
     */
    'currentStep': number;
    /**
     * 프로필 생성 완료 여부
     * @type {boolean}
     * @memberof OnboardingStateResponseDto
     */
    'profileCreated': boolean;
    /**
     * 백준 인증 완료 여부
     * @type {boolean}
     * @memberof OnboardingStateResponseDto
     */
    'baekjoonVerified': boolean;
    /**
     * 스킬 분석 완료 여부
     * @type {boolean}
     * @memberof OnboardingStateResponseDto
     */
    'skillAnalysisCompleted': boolean;
    /**
     * 멘토 프로필 생성 완료 여부
     * @type {boolean}
     * @memberof OnboardingStateResponseDto
     */
    'mentorProfileCreated': boolean;
    /**
     * 온보딩 완료 여부
     * @type {boolean}
     * @memberof OnboardingStateResponseDto
     */
    'isCompleted': boolean;
    /**
     * 백준 연동 완료 여부
     * @type {boolean}
     * @memberof OnboardingStateResponseDto
     */
    'hasBaekjoonLinked': boolean;
    /**
     * 온보딩 완료 일시
     * @type {string}
     * @memberof OnboardingStateResponseDto
     */
    'completedAt'?: string;
}

