/* tslint:disable */
/* eslint-disable */
/**
 * CotePT API
 * 코딩 테스트 멘토링 플랫폼 API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ResetPasswordRequestDto
 */
export interface ResetPasswordRequestDto {
    /**
     * 사용자 이메일
     * @type {string}
     * @memberof ResetPasswordRequestDto
     */
    'email': string;
    /**
     * 인증 ID (인증 코드 발송 후 받은 ID)
     * @type {string}
     * @memberof ResetPasswordRequestDto
     */
    'verificationId': string;
    /**
     * 인증 코드
     * @type {string}
     * @memberof ResetPasswordRequestDto
     */
    'verificationCode': string;
    /**
     * 새 비밀번호
     * @type {string}
     * @memberof ResetPasswordRequestDto
     */
    'newPassword': string;
}

