/* tslint:disable */
/* eslint-disable */
/**
 * CotePT API
 * 코딩 테스트 멘토링 플랫폼 API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ResetPasswordResponseDto
 */
export interface ResetPasswordResponseDto {
    /**
     * 비밀번호 재설정 성공 여부
     * @type {boolean}
     * @memberof ResetPasswordResponseDto
     */
    'success': boolean;
    /**
     * 재설정 완료 시간
     * @type {string}
     * @memberof ResetPasswordResponseDto
     */
    'resetAt': string;
    /**
     * 응답 메시지
     * @type {string}
     * @memberof ResetPasswordResponseDto
     */
    'message': string;
}

