/* tslint:disable */
/* eslint-disable */
/**
 * CotePT API
 * 코딩 테스트 멘토링 플랫폼 API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AuthType } from './auth-type';

/**
 * 
 * @export
 * @interface SendVerificationCodeRequestDto
 */
export interface SendVerificationCodeRequestDto {
    /**
     * 인증 유형
     * @type {AuthType}
     * @memberof SendVerificationCodeRequestDto
     */
    'authType': AuthType;
    /**
     * 인증 대상 (이메일 또는 전화번호)
     * @type {string}
     * @memberof SendVerificationCodeRequestDto
     */
    'target': string;
}



