/* tslint:disable */
/* eslint-disable */
/**
 * CotePT API
 * 코딩 테스트 멘토링 플랫폼 API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TagDto
 */
export interface TagDto {
    /**
     * 태그 키
     * @type {string}
     * @memberof TagDto
     */
    'key': string;
    /**
     * 태그 이름
     * @type {string}
     * @memberof TagDto
     */
    'name': string;
}

