/* tslint:disable */
/* eslint-disable */
/**
 * CotePT API
 * 코딩 테스트 멘토링 플랫폼 API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TagInfoDto } from './tag-info-dto';

/**
 * 
 * @export
 * @interface TagStatisticsResponseDto
 */
export interface TagStatisticsResponseDto {
    /**
     * 사용자 ID
     * @type {string}
     * @memberof TagStatisticsResponseDto
     */
    'userId': string;
    /**
     * 백준 ID
     * @type {string}
     * @memberof TagStatisticsResponseDto
     */
    'handle': string;
    /**
     * 태그별 통계 목록
     * @type {Array<TagInfoDto>}
     * @memberof TagStatisticsResponseDto
     */
    'tags': Array<TagInfoDto>;
    /**
     * 총 태그 수
     * @type {number}
     * @memberof TagStatisticsResponseDto
     */
    'totalTagCount': number;
    /**
     * 총 해결한 문제 수
     * @type {number}
     * @memberof TagStatisticsResponseDto
     */
    'totalSolvedCount': number;
    /**
     * 평균 레이팅
     * @type {number}
     * @memberof TagStatisticsResponseDto
     */
    'averageRating': number;
    /**
     * 마지막 업데이트 시간
     * @type {string}
     * @memberof TagStatisticsResponseDto
     */
    'lastUpdated': string;
}

