/* tslint:disable */
/* eslint-disable */
/**
 * CotePT API
 * 코딩 테스트 멘토링 플랫폼 API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TagInfoDto
 */
export interface TagInfoDto {
    /**
     * 태그 ID
     * @type {number}
     * @memberof TagInfoDto
     */
    'tagId': number;
    /**
     * 태그 키 (영문)
     * @type {string}
     * @memberof TagInfoDto
     */
    'key': string;
    /**
     * 태그 이름 (한국어)
     * @type {string}
     * @memberof TagInfoDto
     */
    'nameKo': string;
    /**
     * 해결한 문제 수
     * @type {number}
     * @memberof TagInfoDto
     */
    'problemCount': number;
    /**
     * 태그별 레이팅
     * @type {number}
     * @memberof TagInfoDto
     */
    'rating': number;
    /**
     * 문제별 레이팅 합계
     * @type {number}
     * @memberof TagInfoDto
     */
    'ratingByProblemsSum': number;
    /**
     * 클래스별 레이팅
     * @type {number}
     * @memberof TagInfoDto
     */
    'ratingByClass': number;
    /**
     * 해결 수별 레이팅
     * @type {number}
     * @memberof TagInfoDto
     */
    'ratingBySolvedCount': number;
}

