/* tslint:disable */
/* eslint-disable */
/**
 * CotePT API
 * 코딩 테스트 멘토링 플랫폼 API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TopTagDto } from './top-tag-dto';

/**
 * 
 * @export
 * @interface TagStatisticsOutputDto
 */
export interface TagStatisticsOutputDto {
    /**
     * 백준 사용자 핸들
     * @type {string}
     * @memberof TagStatisticsOutputDto
     */
    'handle': string;
    /**
     * 상위 태그 목록 (해결한 문제 수 기준)
     * @type {Array<TopTagDto>}
     * @memberof TagStatisticsOutputDto
     */
    'tags': Array<TopTagDto>;
    /**
     * 총 태그 수
     * @type {number}
     * @memberof TagStatisticsOutputDto
     */
    'totalTagCount': number;
    /**
     * 총 해결한 문제 수
     * @type {number}
     * @memberof TagStatisticsOutputDto
     */
    'totalSolvedCount': number;
    /**
     * 티어별 통계 (티어명: 문제 수)
     * @type {object}
     * @memberof TagStatisticsOutputDto
     */
    'tierStats': object;
    /**
     * 통계 데이터가 마지막으로 동기화된 시간
     * @type {string}
     * @memberof TagStatisticsOutputDto
     */
    'lastSynced': string;
}

