/* tslint:disable */
/* eslint-disable */
/**
 * CotePT API
 * 코딩 테스트 멘토링 플랫폼 API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Tier color hex code
 * @export
 * @enum {string}
 */

export enum TierColor {
    _2D2D2D = '#2D2D2D',
    AD5600 = '#AD5600',
    AD56002 = '#AD5600',
    AD56003 = '#AD5600',
    AD56004 = '#AD5600',
    AD56005 = '#AD5600',
    _435F7A = '#435F7A',
    _435F7A2 = '#435F7A',
    _435F7A3 = '#435F7A',
    _435F7A4 = '#435F7A',
    _435F7A5 = '#435F7A',
    EC9A00 = '#EC9A00',
    EC9A002 = '#EC9A00',
    EC9A003 = '#EC9A00',
    EC9A004 = '#EC9A00',
    EC9A005 = '#EC9A00',
    _27E2A4 = '#27E2A4',
    _27E2A42 = '#27E2A4',
    _27E2A43 = '#27E2A4',
    _27E2A44 = '#27E2A4',
    _27E2A45 = '#27E2A4',
    _00D2F0 = '#00D2F0',
    _00D2F02 = '#00D2F0',
    _00D2F03 = '#00D2F0',
    _00D2F04 = '#00D2F0',
    _00D2F05 = '#00D2F0',
    FF0062 = '#FF0062',
    FF00622 = '#FF0062',
    FF00623 = '#FF0062',
    FF00624 = '#FF0062',
    FF00625 = '#FF0062',
    B491FF = '#B491FF'
}



