/* tslint:disable */
/* eslint-disable */
/**
 * CotePT API
 * 코딩 테스트 멘토링 플랫폼 API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Tier display name
 * @export
 * @enum {string}
 */

export enum TierName {
    Unrated = 'Unrated',
    BronzeV = 'BronzeV',
    BronzeIV = 'BronzeIV',
    BronzeIII = 'BronzeIII',
    BronzeII = 'BronzeII',
    BronzeI = 'BronzeI',
    SilverV = 'SilverV',
    SilverIV = 'SilverIV',
    SilverIII = 'SilverIII',
    SilverII = 'SilverII',
    SilverI = 'SilverI',
    GoldV = 'GoldV',
    GoldIV = 'GoldIV',
    GoldIII = 'GoldIII',
    GoldII = 'GoldII',
    GoldI = 'GoldI',
    PlatinumV = 'PlatinumV',
    PlatinumIV = 'PlatinumIV',
    PlatinumIII = 'PlatinumIII',
    PlatinumII = 'PlatinumII',
    PlatinumI = 'PlatinumI',
    DiamondV = 'DiamondV',
    DiamondIV = 'DiamondIV',
    DiamondIII = 'DiamondIII',
    DiamondII = 'DiamondII',
    DiamondI = 'DiamondI',
    RubyV = 'RubyV',
    RubyIV = 'RubyIV',
    RubyIII = 'RubyIII',
    RubyII = 'RubyII',
    RubyI = 'RubyI',
    Master = 'Master'
}



