/* tslint:disable */
/* eslint-disable */
/**
 * CotePT API
 * 코딩 테스트 멘토링 플랫폼 API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TagDto } from './tag-dto';

/**
 * 
 * @export
 * @interface TopTagDto
 */
export interface TopTagDto {
    /**
     * 태그 정보
     * @type {TagDto}
     * @memberof TopTagDto
     */
    'tag': TagDto;
    /**
     * 해당 태그로 해결한 문제 수
     * @type {number}
     * @memberof TopTagDto
     */
    'solvedCount': number;
}

