/* tslint:disable */
/* eslint-disable */
/**
 * CotePT API
 * 코딩 테스트 멘토링 플랫폼 API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateMentorProfileDto
 */
export interface UpdateMentorProfileDto {
    /**
     * 백준 티어 표시 여부
     * @type {boolean}
     * @memberof UpdateMentorProfileDto
     */
    'baekjoonTierDisplay': boolean;
    /**
     * 멘토의 기술 스택 및 직무 태그 ID 목록
     * @type {Array<number>}
     * @memberof UpdateMentorProfileDto
     */
    'tagIds': Array<number>;
    /**
     * 멘토링 소개 제목
     * @type {string}
     * @memberof UpdateMentorProfileDto
     */
    'introductionTitle'?: string;
    /**
     * 멘토링 소개 내용 (마크다운)
     * @type {string}
     * @memberof UpdateMentorProfileDto
     */
    'introductionContent'?: string;
}

