/* tslint:disable */
/* eslint-disable */
/**
 * CotePT API
 * 코딩 테스트 멘토링 플랫폼 API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateUserRequestDto
 */
export interface UpdateUserRequestDto {
    /**
     * 사용자 로그인 아이디 (6~20자, 영문/숫자/특수문자)
     * @type {string}
     * @memberof UpdateUserRequestDto
     */
    'userId'?: string;
    /**
     * 사용자 이메일
     * @type {string}
     * @memberof UpdateUserRequestDto
     */
    'email'?: string;
    /**
<<<<<<< HEAD
     * 사용자 이름 (2~50자, 한글/영문만 허용)
=======
     * 비밀번호 (8~32자, 대소문자, 숫자, 특수문자 포함)
>>>>>>> dev
     * @type {string}
     * @memberof UpdateUserRequestDto
     */
    'name'?: string;
    /**
     * 전화번호 (- 없이 숫자만)
     * @type {string}
     * @memberof UpdateUserRequestDto
     */
    'phoneNumber'?: string;
}

