/* tslint:disable */
/* eslint-disable */
/**
 * CotePT API
 * 코딩 테스트 멘토링 플랫폼 API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateUserProfileRequestDto
 */
export interface UpdateUserProfileRequestDto {
    /**
     * 닉네임 (2~50자, 한글/영문/숫자만 허용)
     * @type {string}
     * @memberof UpdateUserProfileRequestDto
     */
    'nickname'?: string;
    /**
     * 자기소개 (280자 이하, 트위터 스타일)
     * @type {string}
     * @memberof UpdateUserProfileRequestDto
     */
    'introduce'?: string;
    /**
     * 프로필 이미지 URL
     * @type {string}
     * @memberof UpdateUserProfileRequestDto
     */
    'profileImageUrl'?: string;
    /**
     * 실명 (2~50자, 한글/영문만 허용)
     * @type {string}
     * @memberof UpdateUserProfileRequestDto
     */
    'fullName'?: string;
}

