/* tslint:disable */
/* eslint-disable */
/**
 * CotePT API
 * 코딩 테스트 멘토링 플랫폼 API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserDeletionResponseDto
 */
export interface UserDeletionResponseDto {
    /**
     * 삭제 성공 여부
     * @type {boolean}
     * @memberof UserDeletionResponseDto
     */
    'success': boolean;
    /**
     * 삭제된 사용자 ID
     * @type {string}
     * @memberof UserDeletionResponseDto
     */
    'deletedUserId': string;
    /**
     * 삭제 완료 시간
     * @type {string}
     * @memberof UserDeletionResponseDto
     */
    'deletedAt': string;
    /**
     * 응답 메시지
     * @type {string}
     * @memberof UserDeletionResponseDto
     */
    'message': string;
}

