/* tslint:disable */
/* eslint-disable */
/**
 * CotePT API
 * 코딩 테스트 멘토링 플랫폼 API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { UserProfileDto } from './user-profile-dto';

/**
 * 
 * @export
 * @interface UserProfileUpsertResponseDto
 */
export interface UserProfileUpsertResponseDto {
    /**
     * 처리된 사용자 프로필 정보
     * @type {UserProfileDto}
     * @memberof UserProfileUpsertResponseDto
     */
    'profile': UserProfileDto;
    /**
     * 새로 생성된 프로필인지 여부
     * @type {boolean}
     * @memberof UserProfileUpsertResponseDto
     */
    'isNew': boolean;
    /**
     * 응답 메시지
     * @type {string}
     * @memberof UserProfileUpsertResponseDto
     */
    'message': string;
    /**
     * 처리 유형
     * @type {string}
     * @memberof UserProfileUpsertResponseDto
     */
    'operation': Operation;
    /**
     * 수정된 필드 목록 (수정의 경우만)
     * @type {Array<string>}
     * @memberof UserProfileUpsertResponseDto
     */
    'updatedFields'?: Array<string>;
}

/**
    * @export
    * @enum {string}
    */
export enum Operation {
    created = 'created',
    updated = 'updated'
}


