/* tslint:disable */
/* eslint-disable */
/**
 * CotePT API
 * 코딩 테스트 멘토링 플랫폼 API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { UserRole } from './user-role';
// May contain unused imports in some cases
// @ts-ignore
import type { UserStatus } from './user-status';

/**
 * 
 * @export
 * @interface UserResponseDto
 */
export interface UserResponseDto {
    /**
     * 사용자 고유 ID
     * @type {string}
     * @memberof UserResponseDto
     */
    'id': string;
    /**
     * 사용자 이메일
     * @type {string}
     * @memberof UserResponseDto
     */
    'email': string;
    /**
     * 사용자 역할
     * @type {UserRole}
     * @memberof UserResponseDto
     */
    'role': UserRole;
    /**
     * 사용자 상태
     * @type {UserStatus}
     * @memberof UserResponseDto
     */
    'status': UserStatus;
    /**
     * 사용자 생성일
     * @type {string}
     * @memberof UserResponseDto
     */
    'createdAt': string;
    /**
     * 사용자 정보 수정일
     * @type {string}
     * @memberof UserResponseDto
     */
    'updatedAt': string;
    /**
     * 사용자 이름
     * @type {string}
     * @memberof UserResponseDto
     */
    'name'?: string;
    /**
     * 전화번호
     * @type {string}
     * @memberof UserResponseDto
     */
    'phoneNumber'?: string;
    /**
     * 전화번호 인증 여부
     * @type {boolean}
     * @memberof UserResponseDto
     */
    'phoneVerified'?: boolean;
    /**
     * 마지막 로그인 일시
     * @type {string}
     * @memberof UserResponseDto
     */
    'lastLoginAt'?: string;
}



