/* tslint:disable */
/* eslint-disable */
/**
 * CotePT API
 * 코딩 테스트 멘토링 플랫폼 API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { UserDto } from './user-dto';

/**
 * 
 * @export
 * @interface UserListResponseDto
 */
export interface UserListResponseDto {
    /**
     * 사용자 목록
     * @type {Array<UserDto>}
     * @memberof UserListResponseDto
     */
    'users': Array<UserDto>;
    /**
     * 총 사용자 수
     * @type {number}
     * @memberof UserListResponseDto
     */
    'totalCount': number;
    /**
     * 현재 페이지
     * @type {number}
     * @memberof UserListResponseDto
     */
    'currentPage': number;
    /**
     * 페이지당 항목 수
     * @type {number}
     * @memberof UserListResponseDto
     */
    'pageSize': number;
    /**
     * 총 페이지 수
     * @type {number}
     * @memberof UserListResponseDto
     */
    'totalPages': number;
    /**
     * 다음 페이지 존재 여부
     * @type {boolean}
     * @memberof UserListResponseDto
     */
    'hasNext': boolean;
    /**
     * 이전 페이지 존재 여부
     * @type {boolean}
     * @memberof UserListResponseDto
     */
    'hasPrevious': boolean;
}

