/* tslint:disable */
/* eslint-disable */
/**
 * CotePT API
 * 코딩 테스트 멘토링 플랫폼 API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { UserRole } from './user-role';
// May contain unused imports in some cases
// @ts-ignore
import type { UserStatus } from './user-status';

/**
 * 
 * @export
 * @interface UserDto
 */
export interface UserDto {
    /**
     * 사용자 고유 IDX (자동 증가 기본키)
     * @type {number}
     * @memberof UserDto
     */
    'idx': number;
    /**
     * 사용자 로그인 아이디 (6~20자, 영문/숫자/특수문자)
     * @type {string}
     * @memberof UserDto
     */
    'userId': string;
    /**
     * 사용자 이메일
     * @type {string}
     * @memberof UserDto
     */
    'email': string;
    /**
     * 사용자 역할
     * @type {UserRole}
     * @memberof UserDto
     */
    'role': UserRole;
    /**
     * 사용자 상태
     * @type {UserStatus}
     * @memberof UserDto
     */
    'status': UserStatus;
    /**
     * 사용자 생성일
     * @type {string}
     * @memberof UserDto
     */
    'createdAt': string;
    /**
     * 사용자 정보 수정일
     * @type {string}
     * @memberof UserDto
     */
    'updatedAt': string;
    /**
     * 비밀번호 (8~32자, 대소문자, 숫자, 특수문자 포함)
     * @type {string}
     * @memberof UserDto
     */
<<<<<<< HEAD
    'password'?: string;
    /**
     * 사용자 이름 (2~50자, 한글/영문만 허용)
     * @type {string}
     * @memberof UserDto
     */
=======
>>>>>>> dev
    'name'?: string;
    /**
     * 전화번호 (- 없이 숫자만)
     * @type {string}
     * @memberof UserDto
     */
    'phoneNumber'?: string;
    /**
     * 전화번호 인증 여부
     * @type {boolean}
     * @memberof UserDto
     */
    'phoneVerified'?: boolean;
    /**
     * 마지막 로그인 일시
     * @type {string}
     * @memberof UserDto
     */
    'lastLoginAt'?: string;
}



