/* tslint:disable */
/* eslint-disable */
/**
 * CotePT API
 * 코딩 테스트 멘토링 플랫폼 API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserProfileDto
 */
export interface UserProfileDto {
    /**
     * 프로필 ID (자동증가 기본키)
     * @type {number}
     * @memberof UserProfileDto
     */
    'idx': number;
    /**
     * 사용자 로그인 아이디 (6~20자, 영문/숫자/특수문자)
     * @type {string}
     * @memberof UserProfileDto
     */
    'userId': string;
    /**
     * 닉네임 (2~50자, 한글/영문만 허용)
     * @type {string}
     * @memberof UserProfileDto
     */
    'nickname': string;
    /**
     * 생성일시
     * @type {string}
     * @memberof UserProfileDto
     */
    'createdAt': string;
    /**
     * 수정일시
     * @type {string}
     * @memberof UserProfileDto
     */
    'updatedAt': string;
    /**
     * 자기소개 (280자 이하, 트위터 스타일)
     * @type {string}
     * @memberof UserProfileDto
     */
    'introduce'?: string;
    /**
     * 프로필 이미지 URL
     * @type {string}
     * @memberof UserProfileDto
     */
    'profileImageUrl'?: string;
}

