/* tslint:disable */
/* eslint-disable */
/**
 * CotePT API
 * 코딩 테스트 멘토링 플랫폼 API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface VerificationCodeResponseDto
 */
export interface VerificationCodeResponseDto {
    /**
     * 검증 ID
     * @type {string}
     * @memberof VerificationCodeResponseDto
     */
    'verificationId': string;
    /**
     * 인증 만료 시간 (ISO 형식)
     * @type {string}
     * @memberof VerificationCodeResponseDto
     */
    'expiresAt': string;
}

