/* tslint:disable */
/* eslint-disable */
/**
 * CotePT API
 * 코딩 테스트 멘토링 플랫폼 API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { VerificationStatusType } from './verification-status-type';

/**
 * 
 * @export
 * @interface VerificationStatusResponseDto
 */
export interface VerificationStatusResponseDto {
    /**
     * 인증 세션 ID
     * @type {string}
     * @memberof VerificationStatusResponseDto
     */
    'sessionId': string;
    /**
     * 백준 ID
     * @type {string}
     * @memberof VerificationStatusResponseDto
     */
    'handle': string;
    /**
     * 인증 문자열 (프로필 이름에 설정해야 하는 문자열)
     * @type {string}
     * @memberof VerificationStatusResponseDto
     */
    'verificationString': string;
    /**
     * 인증 상태
     * @type {VerificationStatusType}
     * @memberof VerificationStatusResponseDto
     */
    'status': VerificationStatusType;
    /**
     * 현재 시도 횟수
     * @type {number}
     * @memberof VerificationStatusResponseDto
     */
    'attempts': number;
    /**
     * 최대 시도 횟수
     * @type {number}
     * @memberof VerificationStatusResponseDto
     */
    'maxAttempts': number;
    /**
     * 생성 시간
     * @type {string}
     * @memberof VerificationStatusResponseDto
     */
    'createdAt': string;
    /**
     * 만료 시간
     * @type {string}
     * @memberof VerificationStatusResponseDto
     */
    'expiresAt': string;
    /**
     * 완료 시간 (완료된 경우에만)
     * @type {string}
     * @memberof VerificationStatusResponseDto
     */
    'completedAt'?: string;
    /**
     * 실패 사유 (실패한 경우에만)
     * @type {string}
     * @memberof VerificationStatusResponseDto
     */
    'errorReason'?: string;
}



