/* tslint:disable */
/* eslint-disable */
/**
 * CotePT API
 * 코딩 테스트 멘토링 플랫폼 API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreateMentorProfileDto } from '../types';
// @ts-ignore
import type { DeletionResponseDto } from '../types';
// @ts-ignore
import type { MentorProfileDto } from '../types';
// @ts-ignore
import type { UpdateMentorProfileDto } from '../types';
/**
 * MentorApi - axios parameter creator
 * @export
 */
export const MentorApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 새 멘토 프로필 생성
         * @param {CreateMentorProfileDto} createMentorProfileDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createMentorProfile: async (createMentorProfileDto: CreateMentorProfileDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createMentorProfileDto' is not null or undefined
            assertParamExists('createMentorProfile', 'createMentorProfileDto', createMentorProfileDto)
            const localVarPath = `/api/v1/mentor/profile`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createMentorProfileDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 멘토 프로필 비활성화 (논리적 삭제)
         * @param {number} idx 멘토 프로필 IDX
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteMentorProfile: async (idx: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'idx' is not null or undefined
            assertParamExists('deleteMentorProfile', 'idx', idx)
            const localVarPath = `/api/v1/mentor/profile/{idx}`
                .replace(`{${"idx"}}`, encodeURIComponent(String(idx)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 특정 사용자의 멘토 프로필 정보를 조회합니다.
         * @summary 사용자 ID로 멘토 프로필 조회
         * @param {string} userId 조회할 사용자의 ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMentorProfile: async (userId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getMentorProfile', 'userId', userId)
            const localVarPath = `/api/v1/mentor/profile/{userId}`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 멘토 프로필 영구 삭제 (물리적 삭제)
         * @param {number} idx 멘토 프로필 IDX
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        hardDeleteMentorProfile: async (idx: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'idx' is not null or undefined
            assertParamExists('hardDeleteMentorProfile', 'idx', idx)
            const localVarPath = `/api/v1/mentor/profile/{idx}/permanent`
                .replace(`{${"idx"}}`, encodeURIComponent(String(idx)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 멘토 프로필 정보 수정 (PUT)
         * @param {number} idx 멘토 프로필 IDX
         * @param {UpdateMentorProfileDto} updateMentorProfileDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateMentorProfile: async (idx: number, updateMentorProfileDto: UpdateMentorProfileDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'idx' is not null or undefined
            assertParamExists('updateMentorProfile', 'idx', idx)
            // verify required parameter 'updateMentorProfileDto' is not null or undefined
            assertParamExists('updateMentorProfile', 'updateMentorProfileDto', updateMentorProfileDto)
            const localVarPath = `/api/v1/mentor/profile/{idx}`
                .replace(`{${"idx"}}`, encodeURIComponent(String(idx)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateMentorProfileDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MentorApi - functional programming interface
 * @export
 */
export const MentorApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MentorApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary 새 멘토 프로필 생성
         * @param {CreateMentorProfileDto} createMentorProfileDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createMentorProfile(createMentorProfileDto: CreateMentorProfileDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MentorProfileDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createMentorProfile(createMentorProfileDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MentorApi.createMentorProfile']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 멘토 프로필 비활성화 (논리적 삭제)
         * @param {number} idx 멘토 프로필 IDX
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteMentorProfile(idx: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DeletionResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteMentorProfile(idx, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MentorApi.deleteMentorProfile']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 특정 사용자의 멘토 프로필 정보를 조회합니다.
         * @summary 사용자 ID로 멘토 프로필 조회
         * @param {string} userId 조회할 사용자의 ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMentorProfile(userId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MentorProfileDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMentorProfile(userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MentorApi.getMentorProfile']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 멘토 프로필 영구 삭제 (물리적 삭제)
         * @param {number} idx 멘토 프로필 IDX
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async hardDeleteMentorProfile(idx: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DeletionResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.hardDeleteMentorProfile(idx, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MentorApi.hardDeleteMentorProfile']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 멘토 프로필 정보 수정 (PUT)
         * @param {number} idx 멘토 프로필 IDX
         * @param {UpdateMentorProfileDto} updateMentorProfileDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateMentorProfile(idx: number, updateMentorProfileDto: UpdateMentorProfileDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MentorProfileDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateMentorProfile(idx, updateMentorProfileDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MentorApi.updateMentorProfile']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * MentorApi - factory interface
 * @export
 */
export const MentorApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MentorApiFp(configuration)
    return {
        /**
         * 
         * @summary 새 멘토 프로필 생성
         * @param {MentorApiCreateMentorProfileRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createMentorProfile(requestParameters: MentorApiCreateMentorProfileRequest, options?: RawAxiosRequestConfig): AxiosPromise<MentorProfileDto> {
            return localVarFp.createMentorProfile(requestParameters.createMentorProfileDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 멘토 프로필 비활성화 (논리적 삭제)
         * @param {MentorApiDeleteMentorProfileRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteMentorProfile(requestParameters: MentorApiDeleteMentorProfileRequest, options?: RawAxiosRequestConfig): AxiosPromise<DeletionResponseDto> {
            return localVarFp.deleteMentorProfile(requestParameters.idx, options).then((request) => request(axios, basePath));
        },
        /**
         * 특정 사용자의 멘토 프로필 정보를 조회합니다.
         * @summary 사용자 ID로 멘토 프로필 조회
         * @param {MentorApiGetMentorProfileRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMentorProfile(requestParameters: MentorApiGetMentorProfileRequest, options?: RawAxiosRequestConfig): AxiosPromise<MentorProfileDto> {
            return localVarFp.getMentorProfile(requestParameters.userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 멘토 프로필 영구 삭제 (물리적 삭제)
         * @param {MentorApiHardDeleteMentorProfileRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        hardDeleteMentorProfile(requestParameters: MentorApiHardDeleteMentorProfileRequest, options?: RawAxiosRequestConfig): AxiosPromise<DeletionResponseDto> {
            return localVarFp.hardDeleteMentorProfile(requestParameters.idx, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 멘토 프로필 정보 수정 (PUT)
         * @param {MentorApiUpdateMentorProfileRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateMentorProfile(requestParameters: MentorApiUpdateMentorProfileRequest, options?: RawAxiosRequestConfig): AxiosPromise<MentorProfileDto> {
            return localVarFp.updateMentorProfile(requestParameters.idx, requestParameters.updateMentorProfileDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MentorApi - interface
 * @export
 * @interface MentorApi
 */
export interface MentorApiInterface {
    /**
     * 
     * @summary 새 멘토 프로필 생성
     * @param {MentorApiCreateMentorProfileRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MentorApiInterface
     */
    createMentorProfile(requestParameters: MentorApiCreateMentorProfileRequest, options?: RawAxiosRequestConfig): AxiosPromise<MentorProfileDto>;

    /**
     * 
     * @summary 멘토 프로필 비활성화 (논리적 삭제)
     * @param {MentorApiDeleteMentorProfileRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MentorApiInterface
     */
    deleteMentorProfile(requestParameters: MentorApiDeleteMentorProfileRequest, options?: RawAxiosRequestConfig): AxiosPromise<DeletionResponseDto>;

    /**
     * 특정 사용자의 멘토 프로필 정보를 조회합니다.
     * @summary 사용자 ID로 멘토 프로필 조회
     * @param {MentorApiGetMentorProfileRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MentorApiInterface
     */
    getMentorProfile(requestParameters: MentorApiGetMentorProfileRequest, options?: RawAxiosRequestConfig): AxiosPromise<MentorProfileDto>;

    /**
     * 
     * @summary 멘토 프로필 영구 삭제 (물리적 삭제)
     * @param {MentorApiHardDeleteMentorProfileRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MentorApiInterface
     */
    hardDeleteMentorProfile(requestParameters: MentorApiHardDeleteMentorProfileRequest, options?: RawAxiosRequestConfig): AxiosPromise<DeletionResponseDto>;

    /**
     * 
     * @summary 멘토 프로필 정보 수정 (PUT)
     * @param {MentorApiUpdateMentorProfileRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MentorApiInterface
     */
    updateMentorProfile(requestParameters: MentorApiUpdateMentorProfileRequest, options?: RawAxiosRequestConfig): AxiosPromise<MentorProfileDto>;

}

/**
 * Request parameters for createMentorProfile operation in MentorApi.
 * @export
 * @interface MentorApiCreateMentorProfileRequest
 */
export interface MentorApiCreateMentorProfileRequest {
    /**
     * 
     * @type {CreateMentorProfileDto}
     * @memberof MentorApiCreateMentorProfile
     */
    readonly createMentorProfileDto: CreateMentorProfileDto
}

/**
 * Request parameters for deleteMentorProfile operation in MentorApi.
 * @export
 * @interface MentorApiDeleteMentorProfileRequest
 */
export interface MentorApiDeleteMentorProfileRequest {
    /**
     * 멘토 프로필 IDX
     * @type {number}
     * @memberof MentorApiDeleteMentorProfile
     */
    readonly idx: number
}

/**
 * Request parameters for getMentorProfile operation in MentorApi.
 * @export
 * @interface MentorApiGetMentorProfileRequest
 */
export interface MentorApiGetMentorProfileRequest {
    /**
     * 조회할 사용자의 ID
     * @type {string}
     * @memberof MentorApiGetMentorProfile
     */
    readonly userId: string
}

/**
 * Request parameters for hardDeleteMentorProfile operation in MentorApi.
 * @export
 * @interface MentorApiHardDeleteMentorProfileRequest
 */
export interface MentorApiHardDeleteMentorProfileRequest {
    /**
     * 멘토 프로필 IDX
     * @type {number}
     * @memberof MentorApiHardDeleteMentorProfile
     */
    readonly idx: number
}

/**
 * Request parameters for updateMentorProfile operation in MentorApi.
 * @export
 * @interface MentorApiUpdateMentorProfileRequest
 */
export interface MentorApiUpdateMentorProfileRequest {
    /**
     * 멘토 프로필 IDX
     * @type {number}
     * @memberof MentorApiUpdateMentorProfile
     */
    readonly idx: number

    /**
     * 
     * @type {UpdateMentorProfileDto}
     * @memberof MentorApiUpdateMentorProfile
     */
    readonly updateMentorProfileDto: UpdateMentorProfileDto
}

/**
 * MentorApi - object-oriented interface
 * @export
 * @class MentorApi
 * @extends {BaseAPI}
 */
export class MentorApi extends BaseAPI implements MentorApiInterface {
    /**
     * 
     * @summary 새 멘토 프로필 생성
     * @param {MentorApiCreateMentorProfileRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MentorApi
     */
    public createMentorProfile(requestParameters: MentorApiCreateMentorProfileRequest, options?: RawAxiosRequestConfig) {
        return MentorApiFp(this.configuration).createMentorProfile(requestParameters.createMentorProfileDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 멘토 프로필 비활성화 (논리적 삭제)
     * @param {MentorApiDeleteMentorProfileRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MentorApi
     */
    public deleteMentorProfile(requestParameters: MentorApiDeleteMentorProfileRequest, options?: RawAxiosRequestConfig) {
        return MentorApiFp(this.configuration).deleteMentorProfile(requestParameters.idx, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 특정 사용자의 멘토 프로필 정보를 조회합니다.
     * @summary 사용자 ID로 멘토 프로필 조회
     * @param {MentorApiGetMentorProfileRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MentorApi
     */
    public getMentorProfile(requestParameters: MentorApiGetMentorProfileRequest, options?: RawAxiosRequestConfig) {
        return MentorApiFp(this.configuration).getMentorProfile(requestParameters.userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 멘토 프로필 영구 삭제 (물리적 삭제)
     * @param {MentorApiHardDeleteMentorProfileRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MentorApi
     */
    public hardDeleteMentorProfile(requestParameters: MentorApiHardDeleteMentorProfileRequest, options?: RawAxiosRequestConfig) {
        return MentorApiFp(this.configuration).hardDeleteMentorProfile(requestParameters.idx, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 멘토 프로필 정보 수정 (PUT)
     * @param {MentorApiUpdateMentorProfileRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MentorApi
     */
    public updateMentorProfile(requestParameters: MentorApiUpdateMentorProfileRequest, options?: RawAxiosRequestConfig) {
        return MentorApiFp(this.configuration).updateMentorProfile(requestParameters.idx, requestParameters.updateMentorProfileDto, options).then((request) => request(this.axios, this.basePath));
    }
}

